services:
  - type: web
    name: yt-channel-finder
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "false"
      # This tells Puppeteer where to install AND look for the browser
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer

